version: '3.3'
services:
  database:
    image: mysql:5.7.16
    restart: always
    environment:
      MYSQL_DATABASE: 'ssn-docker-db'
      MYSQL_ROOT_PASSWORD: 'docker30RDS'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /home/ubuntu/ssn-docker/dababase:/var/lib/mysql
  
  backend:
    build:
      context: .
      dockerfile: dockerfile-backend
    restart: always
    ports:
      - '8080:8080'
      
  frontend:
    build:
      context: .
      dockerfile: dockerfile-frontend
    restart: always
    ports:
      - '80:8000'